import tkinter as tk

def janela_cadastro_ferramentas():
    cadastro_ferramentas = tk.Toplevel()
    cadastro_ferramentas.title('Janela de Cadastro de Ferramentas')
    cadastro_ferramentas.iconphoto(False, tk.PhotoImage(file='ico/tools.png'))
    cadastro_ferramentas.configure(background='#B9B7BD')
    cadastro_ferramentas.geometry('700x500')
    cadastro_ferramentas.resizable(True, True)
    cadastro_ferramentas.maxsize(width= 900, height=600) # dimensões máximas
    cadastro_ferramentas.minsize(width= 400, height= 300) # dimensões mínimas
    codigo_ferramenta = tk.Label(cadastro_ferramentas, text='Código da Ferramenta:', bg='#ffd')
    codigo_ferramenta.place(relx=0.05, rely=0.02, relwidth= 0.25, relheight= 0.05)
    vcodigo_ferramenta = tk.Entry(cadastro_ferramentas)
    vcodigo_ferramenta.place(relx= 0.35, rely=0.02, relwidth=0.5, relheight=0.05)
    descricao_ferramenta = tk.Label(cadastro_ferramentas, text= 'Descrição da Ferramenta:', bg= '#ffd')
    descricao_ferramenta.place(relx= 0.05, rely= 0.08, relwidth= 0.25, relheight= 0.05)
    vdescricao_ferramenta = tk.Entry(cadastro_ferramentas)
    vdescricao_ferramenta.place(relx = 0.35, rely= 0.08, relwidth= 0.5, relheight= 0.05)
    fabricante = tk.Label(cadastro_ferramentas, text='Fabricante: ', bg='#ffd')
    fabricante.place(relx= 0.05, rely = 0.14, relwidth= 0.25, relheight=0.05)
    vfabricante = tk.Entry(cadastro_ferramentas)
    vfabricante.place(relx= 0.35, rely= 0.14, relwidth= 0.5, relheight=0.05)
    voltagem = tk.Label(cadastro_ferramentas, text='Voltagem de Uso:', bg='#ffd')
    voltagem.place(relx=0.05, rely= 0.2, relwidth=0.25, relheight=0.05)
    vvoltagem = tk.Entry(cadastro_ferramentas)
    vvoltagem.place(relx= 0.35, rely = 0.2, relwidth=0.5, relheight=0.05)
    part_number = tk.Label(cadastro_ferramentas, text= 'Part Number:', bg='#ffd')
    part_number.place(relx= 0.05, rely= 0.26, relwidth=0.25, relheight=0.05)
    vpart_number = tk.Entry(cadastro_ferramentas)
    vpart_number.place(relx= 0.35, rely= 0.26, relwidth=0.5, relheight=0.05)
    tamanho = tk.Label(cadastro_ferramentas, text='Tamanho da Ferramenta:', bg='#ffd')
    tamanho.place(relx=0.05, rely= 0.32, relwidth=0.25, relheight=0.05)
    vtamanho = tk.Entry(cadastro_ferramentas)
    vtamanho.place(relx=0.35, rely= 0.32, relwidth=0.5, relheight=0.05)
    unidade_medida = tk.Label(cadastro_ferramentas, text='Unidade de Medida:', bg='#ffd')
    unidade_medida.place(relx= 0.05, rely= 0.38, relwidth=0.25, relheight=0.05)
    vunidade_medida = tk.Entry(cadastro_ferramentas)
    vunidade_medida.place(relx=0.35, rely= 0.38, relwidth= 0.5, relheight=0.05)
    tipo_ferramenta = tk.Label(cadastro_ferramentas, text='Tipo da Ferramenta:', bg='#ffd')
    tipo_ferramenta.place(relx= 0.05, rely=0.44, relwidth=0.25, relheight=0.05)
    vtipo_ferramenta = tk.Entry(cadastro_ferramentas)
    vtipo_ferramenta.place(relx= 0.35, rely=0.44, relwidth=0.5, relheight=0.05)
    material_ferramenta = tk.Label(cadastro_ferramentas, text='Material da Ferramenta', bg='#ffd')
    material_ferramenta.place(relx= 0.05, rely= 0.5, relwidth=0.25, relheight=0.05)
    vmaterial_ferramenta = tk.Entry(cadastro_ferramentas)
    vmaterial_ferramenta.place(relx = 0.35, rely=0.5, relwidth=0.5, relheight=0.05)
    bsalvar = tk.Button(cadastro_ferramentas, text= 'Salvar Cadastro')
    bsalvar.place(relx= 0.29, rely = 0.6, relwidth=0.4, relheight=0.05)


def janela_consulta_ferramentas():
    consulta_ferramentas = tk.Toplevel()
    consulta_ferramentas.title('Janela de Consulta de Ferramentas')
    consulta_ferramentas.iconphoto(False, tk.PhotoImage(file='ico/tools.png'))
    consulta_ferramentas.configure(background='#B9B7BD')
    consulta_ferramentas.geometry('700x500')
    consulta_ferramentas.resizable(True, True)
    consulta_ferramentas.maxsize(width= 900, height=600) # dimensões máximas
    consulta_ferramentas.minsize(width= 400, height= 300) # dimensões mínimas